services:
    - docker:dind

stages:
    - test
    - build

# Run flake8 to check for code quality
# And also optionally run unit tests
tests:
    image: python:3-bullseye
    stage: test
    script:
        - pip install flake8
        - flake8 api
        # Run unit tests
        # - cd api
        # - pip install -r requirements.txt
        # - python -m pytest
# # Build API Image:
# # This job builds the API docker image and pushes it to the GitLab docker registry
# build-api-image:
#   stage: build
#   image: docker:git
#   needs:
#     - tests
#   variables:
#     GITLAB_IMAGE: ${CI_REGISTRY_IMAGE}/api
#   before_script:
#     # $CI_JOB_TOKEN is variable automatically added by Gitlab: see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference
#     - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
#   script:
#     - docker build --tag $GITLAB_IMAGE:latest ./api
#     - docker push $GITLAB_IMAGE:latest
#   only:
#     - main

# # Build the React/JavaScript front-end
# build-front-end-job:
#   stage: build
#   image: node:lts-bullseye
#   needs:
#     - tests
#   script:
#     - cd ghi
#     - npm install
#     - npm run lint
#     - npm run build -- --base=/PROJECT_NAME/
#     # The following line creates a _redirects file to redirect all URLs to index.html
#     # Documentation: https://docs.gitlab.com/ee/user/project/pages/redirects.html#rewrite-all-requests-to-a-root-indexhtml
#     - echo "/* /index.html 200" > dist/_redirects
#   artifacts:
#     paths:
#       - ghi/dist/
